### ISSUE TITLE
media-sound/tuxguitar-1.6.0 "An Ant BuildException has occured: exec returned: 2"

### ISSUE THREAD

**Issue by Mrhnhrm** [domichel/proaudio-gentoo#4]
Hi, and thanks for taking a look.

Merging tuxguitar fails:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (compile-native) on project tuxguitar-jack-linux-x86_64: An Ant BuildException has occured: exec returned: 2`
`[ERROR] around Ant part ...<exec failonerror="true" dir="../../..//TuxGuitar-jack/jni/" executable="make">... @ 4:82 in /var/tmp/portage/media-sound/tuxguitar-1.6.0/work/tuxguitar-1.6.0/build-scripts/native-modules/tuxguitar-jack-linux-x86_64/target/antrun/build-compile-native.xml`

I wonder why it even bothers with JACK, because _fluidjack_ USE flag is disabled.

On a potentially related note, this ebuild fails even earlier if network sandboxing is not disabled (and normally one shouldn't disable network sandboxing):

`[ERROR] Plugin org.apache.maven.plugins:maven-surefire-plugin:3.2.2 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-surefire-plugin:jar:3.2.2: The following artifacts could not be resolved: org.apache.maven.plugins:maven-surefire-plugin:pom:3.2.2 (absent): Could not transfer artifact org.apache.maven.plugins:maven-surefire-plugin:pom:3.2.2 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: Temporary failure in name resolution: Unknown host repo.maven.apache.org: Temporary failure in name resolution -> [Help 1]
org.apache.maven.plugin.PluginResolutionException: Plugin org.apache.maven.plugins:maven-surefire-plugin:3.2.2 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-surefire-plugin:jar:3.2.2
`

[build.log](https://github.com/domichel/proaudio-gentoo/files/14930721/build.log)
[emerge-info.txt](https://github.com/domichel/proaudio-gentoo/files/14930732/emerge-info.txt)

Thanks in advance.

**Comment by domichel** [comment]
Thanks for the report and PR. commit 9b8cfd0 fix it.

**Comment by domichel** [comment]
I think this bug is triggered because the archive at https://github.com/domichel/GenCool/raw/master/distfiles/tuxguitar-${PV}_bdepends.tar.bz2 don't contain the missing dependencies files, and that because they have been installed system wide by portage on my system when I made that archive.

Not sure for the real fix. One solution would be to made that archive on an minimal gentoo installation. Or maybe it is a way to tell ant to download every thing including the already installed dependencies. I will ask on irc::#gentoo-dev-help when I get some time to lock at it..
